version: 2.1

orbs:
  tools: replikativ/clj-tools@0
jobs:
  setup:
    executor: tools/clojurecli
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}
            - deps-
      - run: clojure -e nil
      - save_cache:
          key: deps-{{ checksum "deps.edn" }}
          paths:
            - /home/circleci/.m2
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - replikativ

workflows:
  build-test-and-deploy:
    jobs:
      - setup
      - tools/format:
          requires:
            - setup
      - tools/unittest:
          requires:
            - setup
      - tools/integrationtest-postgresql:
          requires:
            - setup
      - tools/build:
          jarname: "datahike"
          requires:
            - setup
      - tools/deploy-snapshot:
          jarname: "datahike"
          context: clojars-deploy
          filters:
            branches:
              only: development
          requires:
            - setup
            - tools/format
            - tools/unittest
            - tools/integrationtest-postgresql
            - tools/build
      - tools/deploy-release:
          jarname: "datahike"
          context: clojars-deploy
          filters:
            branches:
              only: master
          requires:
            - setup
            - tools/format
            - tools/unittest
            - tools/integrationtest-postgresql
            - tools/build